CREATE TABLE IF NOT EXISTS `LocalAccount` (
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Username` VARCHAR(32) NOT NULL,
`PasswordHash` VARCHAR(64) NOT NULL,
`LastLoginTimeUtc` DATETIME NULL,
`LastLoginIp` VARCHAR(64) NULL,
`CreateTimeUtc` DATETIME NOT NULL) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Menu`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Title` VARCHAR(64) NOT NULL,
`Url` VARCHAR(256) NOT NULL,
`Icon` VARCHAR(64) NULL,
`DisplayOrder` INT NOT NULL,
`IsOpenInNewTab` BOOLEAN NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Post`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Title` VARCHAR(128) NULL,
`Slug` VARCHAR(128) NULL,
`Author` VARCHAR(64) NULL,
`PostContent` LONGTEXT NULL,
`CommentEnabled` BOOLEAN NOT NULL,
`CreateTimeUtc` DATETIME NOT NULL,
`ContentAbstract` VARCHAR(1024) NULL,
`ContentLanguageCode` CHAR(8) NULL,
`IsFeedIncluded` BOOLEAN NOT NULL,
`PubDateUtc` DATETIME NULL,
`LastModifiedUtc` DATETIME NULL,
`IsPublished` BOOLEAN NOT NULL,
`IsFeatured` BOOLEAN NOT NULL,
`IsOriginal` BOOLEAN NOT NULL,
`OriginLink` VARCHAR(256) NULL,
`HeroImageUrl` VARCHAR(256) NULL,
`InlineCss` VARCHAR(2048) NULL,
`IsDeleted` BOOLEAN NOT NULL,
`HashCheckSum` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Tag`(
`Id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
`DisplayName` VARCHAR(32) NULL,
`NormalizedName` VARCHAR(32) NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Category`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`RouteName` VARCHAR(64) NULL,
`DisplayName` VARCHAR(64) NULL,
`Note` VARCHAR(128) NULL) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `BlogConfiguration`(
`Id` INT UNSIGNED PRIMARY KEY NOT NULL,
`CfgKey` VARCHAR(64) NULL,
`CfgValue` TEXT NULL,
`LastModifiedTimeUtc` DATETIME NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `BlogAsset`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Base64Data` TEXT NULL,
`LastModifiedTimeUtc` datetime NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Comment`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Username` VARCHAR(64) NULL,
`Email` VARCHAR(128) NULL,
`IPAddress` VARCHAR(64) NULL,
`CreateTimeUtc` DATETIME NOT NULL,
`CommentContent` TEXT NOT NULL,
`PostId` CHAR(36) NOT NULL,
`IsApproved` BOOLEAN NOT NULL,
CONSTRAINT `FK_Comment_Post` FOREIGN KEY (`PostId`) REFERENCES `Post` (`Id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `CommentReply`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`ReplyContent` TEXT NULL,
`CreateTimeUtc` DATETIME NOT NULL,
`CommentId` CHAR(36) NOT NULL) 
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS  `FriendLink`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Title` VARCHAR(64) NULL,
`LinkUrl` VARCHAR(256) NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `Pingback`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Domain` VARCHAR(256) NULL,
`SourceUrl` VARCHAR(256) NULL,
`SourceTitle` VARCHAR(256) NULL,
`SourceIp` VARCHAR(64) NULL,
`TargetPostId`  CHAR(36) NOT NULL,
`PingTimeUtc` DATETIME NOT NULL,
`TargetPostTitle` VARCHAR(128) NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `PostCategory`(
`PostId`  CHAR(36) NOT NULL,
`CategoryId` CHAR(36) NOT NULL,
PRIMARY KEY (`PostId`,`CategoryId`),
CONSTRAINT `FK_PostCategory_Category` FOREIGN KEY (`CategoryId`) REFERENCES `Category` (`Id`) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT `FK_PostCategory_Post` FOREIGN KEY (`PostId`) REFERENCES `Post` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `PostExtension`(
`PostId`  CHAR(36) PRIMARY KEY NOT NULL,
`Hits` INT NOT NULL,
`Likes` INT NOT NULL,
CONSTRAINT `FK_PostExtension_Post` FOREIGN KEY (`PostId`) REFERENCES `Post` (`Id`) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `PostTag`(
`PostId` CHAR(36) NOT NULL,
`TagId` INT UNSIGNED NOT NULL,
PRIMARY KEY (`PostId`,`TagId`),
CONSTRAINT `FK_PostTag_Post` FOREIGN KEY (`PostId`) REFERENCES `Post` (`Id`) ON DELETE CASCADE,
CONSTRAINT `FK_PostTag_Tag` FOREIGN KEY (`TagId`) REFERENCES `Tag` (`Id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `CustomPage`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Title` VARCHAR(128) NULL,
`Slug` VARCHAR(128) NULL,
`MetaDescription` VARCHAR(256) NULL,
`HtmlContent` TEXT NULL,
`CssContent` TEXT NULL,
`HideSidebar` BOOLEAN NOT NULL,
`IsPublished` BOOLEAN NOT NULL,
`CreateTimeUtc` DATETIME NOT NULL,
`UpdateTimeUtc` DATETIME NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `SubMenu`(
`Id` CHAR(36) PRIMARY KEY NOT NULL,
`Title` VARCHAR(64) NOT NULL,
`Url` VARCHAR(256) NOT NULL,
`IsOpenInNewTab` BOOLEAN NOT NULL,
`MenuId` CHAR(36) NULL,
CONSTRAINT `FK_SubMenu_Menu` FOREIGN KEY (`MenuId`) REFERENCES `Menu` (`Id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;

CREATE TABLE IF NOT EXISTS `BlogTheme`(
`Id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
`ThemeName` VARCHAR(32) NULL,
`CssRules` TEXT NULL,
`AdditionalProps` TEXT NULL,
`ThemeType` INT NOT NULL)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_GENERAL_CI;