DELETE FROM BlogConfiguration

INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (1, 'ContentSettings', '{"EnableComments":true,"RequireCommentReview":true,"UseFriendlyNotFoundImage":true,"EnableWordFilter":false,"PostListPageSize":10,"HotTagAmount":10,"DisharmonyWords":"fuck|shit","ShowCalloutSection":false,"CalloutSectionHtmlPitch":""}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (2, 'NotificationSettings', '{"EnableEmailSending":true,"EnableSsl":true,"SendEmailOnCommentReply":true,"SendEmailOnNewComment":true,"SmtpServerPort":587,"AdminEmail":"","EmailDisplayName":"Moonglade","SmtpPassword":"","SmtpServer":"","SmtpUserName":"","BannedMailDomain":""}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (3, 'FeedSettings', '{"RssItemCount":20,"RssCopyright":"(c) {year} Moonglade","RssDescription":"Latest posts from Moonglade","RssTitle":"Moonglade","AuthorName":"Admin","UseFullContent":false}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (4, 'GeneralSettings', '{"OwnerName":"Admin","OwnerEmail":"admin@edi.wang","Description":"Moonglade Admin","ShortDescription":"Moonglade Admin","AvatarBase64":"","SiteTitle":"Moonglade","LogoText":"moonglade","MetaKeyword":"moonglade","MetaDescription":"Just another .NET blog system","Copyright":"[c] 2021","SideBarCustomizedHtmlPitch":"","FooterCustomizedHtmlPitch":"","UserTimeZoneBaseUtcOffset":"08:00:00","TimeZoneId":"China Standard Time","AutoDarkLightTheme":true}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (5, 'WatermarkSettings', '{"IsEnabled":true,"KeepOriginImage":false,"FontSize":20,"WatermarkText":"Moonglade"}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (6, 'AdvancedSettings', '{"DNSPrefetchEndpoint":"","EnableOpenGraph":true,"EnablePingBackSend":true,"EnablePingBackReceive":true,"EnableOpenSearch":true,"WarnExternalLink":true,"AllowScriptsInPage":false,"ShowAdminLoginButton":false,"EnablePostRawEndpoint":true}', GETDATE())
INSERT BlogConfiguration (Id, CfgKey, CfgValue, LastModifiedTimeUtc) VALUES (7, 'CustomStyleSheetSettings', '{"EnableCustomCss":false,"CssCode":""}', GETDATE())

DELETE FROM LocalAccount
INSERT LocalAccount(Id, Username, PasswordHash, CreateTimeUtc) VALUES (NEWID(), 'admin', 'JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=', GETDATE())