name: Docker Linux x64 (Preview)

on:
  push:
    branches: [ master ]
    #paths:
    #- src/**
jobs:

  build:
    if: github.repository == 'EdiWang/Moonglade'
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/moonglade:preview

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
