name: Azure Web App (PROD)

env:
  AZURE_WEBAPP_NAME: ediwang
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        working-directory: ./src/Moonglade.Web
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./src/Moonglade.Web
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/moonglade-release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/moonglade-release

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          clean: true
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE2 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
